# GET http://localhost:3002/rider-coordinates
GET http://localhost:3002/rider-coordinates/123

###

# POST http://localhost:3002/rider-coordinates
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
  "lat": 321.673271,
  "lng": 321.6732714,
  "rider": "123"
}